steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/buttertech-multimodal-agent:$SHORT_SHA', '.']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'buttertech-multimodal-agent',
           '--image', 'europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/buttertech-multimodal-agent:$SHORT_SHA',
           '--region', 'europe-west1',
           '--platform', 'managed',
           '--allow-unauthenticated']

images:
  - 'europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/buttertech-multimodal-agent:$SHORT_SHA'
